[package]
name = "swendsen_wang"
version = "0.1.0"
edition = "2024"

[dependencies]
num = "0.4.3"
num-traits = "0.2.19"
parameter_reader = { git = "https://github.com/so-groenen/rust_parameter_reader.git", version = "0.1.0" }
rand = "0.9.2"
rayon = "1.11.0"
